### ISSUE TITLE
Gitignore... ?

### ISSUE THREAD

**Issue by Petabyte918** [michael-rutledge/millionaire#1] opened 2020-06-05 08:29 UTC
can u share this files? Thanks

client/js/bundle.js
node_modules/
server/question/FastestFingerQuestions.json
server/question/HotSeatQuestions*\.json
script/

**Comment by michael-rutledge** [comment] 2020-06-08 17:58
Oh wow, I never realized anyone might see this, so I apologize for the late response (don't usually come on here to manage my own repos; but now that I know at least one person is following, that will change). Thanks for stopping by!

Anyway, an explanation for each file/directory and why it is on the gitignore, and what you can do about it:

* `client/js/budle.js`: This file is created after running any one of the `build` or `clean*` scripts via `npm run` (see `package.json`). It is the js file used by the client on `client/index.html`. It is a result of using the [browserify](http://browserify.org/) library. The purpose of that library is to allow for `require` statements in the js code client-side by automatically compiling all client scripts into one js file so that the `require` statements. work. The file is on the `.gitignore` because it will be automatically generated upon running the app on your end. 

* `node_modules`: These are the dependencies for the project. They are ignored here because they will artificially inflate the size of the repo. Running `npm install` on your end will give you everything you need.

* `server/question/FastestFingerQuestions.json` and `HotSeatQuestions*.json`: This is one that I am still unsure on. I thought it best to leave these up to whoever is working on the repo, wherever they may be. I made this call because I ripped all of my hotseat questions from [Open Trivia DB](https://opentdb.com/) and stored them locally. Also, some of my fastest finger questions I ripped straight from the show. Furthermore, I don't want this repo to serve as a cheat sheet for anyone playing or planning on playing. If you want my questions, I'm sure we can find a way for me to send them to you directly. Otherwise, if you want questions, you are allowed to find a better source of questions as long as they conform to the data structures (this means I have to un-ignore the hot seat question test json files, which display the required format; I won't close this issue until those files are on the repo). Let me know what you think.

* `script/`: This is a directory for personal scripts that have no impact on the actual app and are not part of the running process at all. Examples might include scripts that rename files or format code. For me, I have a script that updates my hot seat question bank by scrubbing [Open Trivia DB](https://opentdb.com/).

* NOTE: **For all of these files,  I will update the `.gitignore` and/or README with comments to clarify the purpose of their respective ignores, and I won't close this issue until I do so.**

**Comment by michael-rutledge** [comment] 2020-06-08 18:03
Oh also, there is a new directory in there, `client/assets`. That is for the custom fonts of the game. See `client/style/style.css` for their use. The fonts are not on the repo for copyright/legal reasons. If you would like to get the fonts, they are:

* [Copperplate Gothic](https://docs.microsoft.com/en-us/typography/font-list/copperplate-gothic)

* [ITC Conduit Bold](https://www.fonts.com/font/itc/conduititcstd/bold)

It should be noted that you can ignore these font files (or even replace them with your own font replacements) and the game will still work as intended, just with different fonts.

**Comment by michael-rutledge** [comment] 2020-07-07 05:58
Marking closed as README has finally been updated. `script` directory is now out of the `.gitignore`.

**Closed by michael-rutledge** 2020-07-07 05:58 UTC
Labels: documentation
